### ISSUE TITLE
Both 'Heating' and 'Hot Water' symbols are lit when either pump is on

### ISSUE THREAD

**Issue by MrTimbones** [MyForest/mmspheatpump#16]
The top line of the app shows when the heat pump is active, by shading the 'Space Heating' and 'Hot Water' symbols in red based on their respective pump activity. However, on my system, both symbols are always lit when _either_ pump is running.

For example, right now, WaterPump4Status (hot water) is high, and WaterPump2Status (heating) is low, and yet both of them are highlighted in red. Which is generally not possible for this model of heat pump.

![image](https://user-images.githubusercontent.com/75039652/155412091-d9067dd4-1b34-44e9-85ef-c5bd3a5ea0d9.png)

![image](https://user-images.githubusercontent.com/75039652/155412468-38095630-b9bb-4ce0-8315-a8d395eb5fcb.png)

**Comment by MrTimbones** [comment]
It looks like it's because `feedMeta.value` is a string, and `if (feedMeta.value)` evaluates as true for both "1" and "0".

**Comment by MyForest** [comment]
I was pondering how you were getting a string.

In my "post to EmonCMS" code I have a thing like this to convert a boolean to `0` or `1` as an integer. It's pretty high tech:

```Python
b = bool(thing_being_posted)
v = 0
if b:
    v = 1
to_post = v
```

Are you posting it as a string? I didn't think you could post strings to EmonCMS. Is it possible that your setup is getting strings when you are requesting data from `feed/data.json`? Inquiring minds want to know.

**Comment by MrTimbones** [comment]
I'm definitely posting numbers to EmonCMS, but when I look at `../feed/list.json` that the MMSP app is requesting, all the values are represented as strings, no matter which storage engine has been used.

![image](https://user-images.githubusercontent.com/75039652/155421541-d52936ab-fad0-4d06-a94e-62d16b08b14c.png)

:man_shrugging:

**Comment by MyForest** [comment]
Hmm, that's pretty peculiar.

When I'm calling it I get a result including the pump data like this:

```JSON
	"42": {
		"id": "493",
		"userid": "1",
		"name": "WaterPump1Status",
		"datatype": "1",
		"tag": "ecodan",
		"public": "",
		"size": "4584304",
		"engine": "5",
		"unit": "",
		"time": 1638686280,
		"value": 0,
		"start_time": 1569922020,
		"end_time": 1638686280,
		"interval": 60
	}
```

**Comment by MrTimbones** [comment]
Do you have REDIS enabled? I never managed to get it to work, so I've been using EmonCMS without it.

That means the list of feeds and values are stored in MySQL, and it seems that when [feed_model.php](https://github.com/emoncms/emoncms/blob/master/Modules/feed/feed_model.php) requests all the data with [mysql_get_user_feeds](https://github.com/emoncms/emoncms/blob/9a4fca55ee062d0130f72adf30e71159ea5f56c9/Modules/feed/feed_model.php#L396), the values are strings, despite the schema of the table definitely storing `value` as a `double`.

This can be fixed by adding `$row['value'] = floatval($row['value'])` within the `$row` loop, but this shouldn't be necessary; mysqli usually returns data in the correct type, I thought.

**Comment by MyForest** [comment]
Yes @MrTimbones 

I'm Docker-based for absolutely everything so you can imagine I'm running something like this:

```
MARIA_DB=$(docker run \
-d \
-v a:/var/lib/mysql/emoncms \
-v b:/etc/mysql/conf.d:ro \
-e MYSQL_ROOT_PASSWORD \
mariadb )

REDIS=$(docker run \
-d \
-v c:/data \
redis:5 )

echo "Setting up emoncms..."

docker run \
-d \
-e MYSQL_PASSWORD \
--link ${MARIA_DB}:db \
--link ${REDIS}:redis \
-v d:/var/opt/emoncms/phpfina/ \
-v e:/var/opt/emoncms/phptimeseries/ \
-P \
myforest/emoncms
```

**Comment by MrTimbones** [comment]
> mysqli usually returns data in the correct type, I thought.

I thought wrong. It turns out that mysqli is returning all fields as strings, regardless of how they are stored in the database.

I'm amazed that anything works at all, seeing as all numeric operations will have depended on PHP's own implicit conversion to real numbers.

**Comment by MyForest** [comment]
What shall we do about this @MrTimbones ? 

Do you want to chase it with EmonCMS and close this issue or would you like to keep it open to track the outcome?

**Comment by MrTimbones** [comment]
I'm happy that we now understand why this fix was necessary, and I've not had any issues elsewhere with EmonCMS, so I think we can close this issue.

**Comment by MyForest** [comment]
Thanks for your help @MrTimbones
