### ISSUE TITLE
Instantaneous CoP figures can be very large - we should smooth them out in the graph

### ISSUE THREAD

**Issue by MyForest** [MyForest/mmspheatpump#2]
Seeing a CoP of 7000% is worrying people and doesn't match how people think about the performance of a heat pump.

We should smooth the CoP out over 5 minutes so it looks more sane.

![image](https://user-images.githubusercontent.com/10685068/75077642-46d35180-54fb-11ea-86a9-d48f2f05d3ae.png)

**Comment by MyForest** [comment]
Using the [CurvedLines](https://github.com/MichaelZinsmaier/CurvedLines) plugin in flot looks promising...

![image](https://user-images.githubusercontent.com/10685068/75118929-7c507a00-5676-11ea-8a45-81678f7a0d40.png)

**Comment by MyForest** [comment]
When there's more data points it looks pretty debatable

![image](https://user-images.githubusercontent.com/10685068/75118951-9f7b2980-5676-11ea-901b-027d55e332b1.png)

**Comment by MyForest** [comment]
With a day's worth of data where there are 1200 points, it's clearly not working. There's no room for it to insert extra points to give the smoothing

![image](https://user-images.githubusercontent.com/10685068/75118970-bfaae880-5676-11ea-8d90-5d113857e759.png)

**Comment by MyForest** [comment]
Even going to just 200 points doesn't look good for a day

![image](https://user-images.githubusercontent.com/10685068/75118992-e23d0180-5676-11ea-8782-1d4075e4d572.png)

**Comment by MyForest** [comment]
We're going to have to smooth the underlying data (as expected)

**Comment by MyForest** [comment]
There is an averaging plugin for flot but it appears to be AWOL

http://jumflot.jumware.com/examples/Experimental/Algorithm.html

**Comment by MyForest** [comment]
This is no good because it's the average of the CoPs. It's needs to be the weighted average.
```

function smooth(feedHistory) {

    return feedHistory.map((row, index, array) => {

        const friends = array.slice(index - 3, index + 3)

        const sum = friends.reduce((p, row) => p + Math.min(row[1], 10), 0)

        const average = sum / friends.length

        return [row[0], average]

    })

}
```

**Comment by MyForest** [comment]
I'm now:

* smoothing over a number of points
* applying an upper-bound to the CoP
* indicating there's no CoP if there's no input

It's still not right.

![image](https://user-images.githubusercontent.com/10685068/75120364-2afab780-5683-11ea-9970-6bea410cbc5c.png)

**Comment by MyForest** [comment]
Still pretty spiky but not terrible. I allowed a CoP even when there's no input for that specific moment.

![image](https://user-images.githubusercontent.com/10685068/75120774-0d7b1d00-5686-11ea-8fb5-288822e3082a.png)

**Comment by MyForest** [comment]
Switched to showing the space and hot water CoP graphs separately so we can compare performance better

![image](https://user-images.githubusercontent.com/10685068/75120921-64352680-5687-11ea-960a-5085437701e4.png)

**Comment by MyForest** [comment]
I've added "nominal" efficiencies for an unnamed air source heat pump.

The CoP display is now OK, but not awesome. At least it's reasonable enough to compare the nominal versus the achieved CoP.

![image](https://user-images.githubusercontent.com/10685068/75122316-2985bb00-5694-11ea-886e-29ff0a38d2c5.png)

**Comment by MrTimbones** [comment]
I feel that the current smoothing of CoP (average of 3 previous, current and 4 following readings) is _too smooth_ and hides some of the detail of how the heat pump is performing. See this plot, where my EcoDan likes to take a breather in the middle of a run:

![image](https://user-images.githubusercontent.com/75039652/199691599-bca0e5e5-5dad-4d18-9231-901d4b3b67e5.png)

I'm experimenting with a smaller window (+/- 1), which I think provides a better view, specifically of that pause in the middle.

![image](https://user-images.githubusercontent.com/75039652/199691856-d542a0e9-166d-42d8-8239-22549de319c8.png)

I also tried a non-symmetric algorithm that only considered past readings, but didn't like that as much.

I'll run with this for a while and report back on how well it works out in practice.

**Comment by MyForest** [comment]
You're quite right @MrTimbones , it's aesthetic so it becomes a personal preference.

I started doing the smoothing when [the community was chatting about the spikes](https://community.openenergymonitor.org/t/an-app-to-review-heat-pump-experiments/13372/11?u=myforest) being misleading.

Perhaps the only way we'll get it so everyone can be happy is to add it as a setting and put in some defaults that meet general approval but that allow people to make their own tweaks?
